CREATE DATABASE controle_presenca;
USE controle_presenca;

CREATE TABLE alunos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ra VARCHAR(20) NOT NULL UNIQUE,
  nome VARCHAR(100) NOT NULL
);

CREATE TABLE presenca (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ra VARCHAR(20) NOT NULL,
  datahora DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ra) REFERENCES alunos(ra)
);
